# Generated by Django 5.2.7 on 2025-10-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0002_instituicao_senha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ofertas_fotos/')),
                ('data_validade_produto', models.DateField()),
                ('data_expiracao_oferta', models.DateTimeField()),
                ('quantidade', models.PositiveIntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_reservada', models.PositiveIntegerField()),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_reservas', to='instituicoes.instituicao')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ofertas.oferta')),
            ],
            options={
                'unique_together': {('oferta', 'instituicao')},
            },
        ),
    ]
