# Generated by Django 5.2.5 on 2025-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nome_proprietario', models.CharField(max_length=150)),
                ('cargo_funcao', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone_proprietario', models.CharField(max_length=20)),
                ('responsavel_tecnico', models.CharField(max_length=150)),
                ('formacao_academica', models.CharField(max_length=150)),
                ('conselho_classe', models.CharField(max_length=50)),
                ('tipo_estabelecimento', models.CharField(max_length=100)),
                ('tipo_manipulacao', models.CharField(max_length=100)),
                ('num_funcionarios', models.PositiveIntegerField()),
                ('num_licenca_sanitaria', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
