# Generated by Django 5.2.5 on 2025-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_alter_estabelecimento_horario_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='num_funcionarios',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
