# Generated by Django 5.2.5 on 2025-10-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('estabelecimentos', '0004_estabelecimento_groups_estabelecimento_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='estabelecimentos_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='estabelecimentos_user_permissions', to='auth.permission'),
        ),
    ]
