# Generated by Django 5.2.5 on 2025-10-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0005_alter_estabelecimento_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='tipo_usuario',
            field=models.CharField(default='estabelecimento', editable=False, max_length=20),
        ),
    ]
