# Generated by Django 5.2.5 on 2025-10-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='senha',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
