# Generated by Django 5.2.5 on 2025-10-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0002_instituicao_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='senha',
        ),
    ]
