# Generated by Django 5.2.5 on 2025-10-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0003_remove_instituicao_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='tipo_usuario',
            field=models.CharField(default='instituicao', editable=False, max_length=20),
        ),
    ]
